### ISSUE TITLE
Minor: able to create a new haircut log without filling out the form

### ISSUE THREAD

**Issue by leemeli** [sheared-sasquatch/sparkclips#45]
Reproduction steps:
Create a new account or login
Go to “My Haircut Log”
Click “Add a New Entry”
Without filling anything out, press “Upload”

**Comment by KyleIWS** [comment]
Because we expect each user to create their own hair log, and make it useful for their needs, there is no reason to prevent users from uploading empty logs if that is what they want to do. Further, empty logs do not alter anyones experience except the user who decided to make an empty log. Further further, they can be deleted.
